[package]
name = "statix"
version = "0.3.5"
edition = "2018"
license = "MIT"
authors = [ "Akshay <nerdy@peppe.rs>" ]
description = "Lints and suggestions for the Nix programming language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.3"
rnix = "0.9.0"
clap = "3.0.0-beta.4"
ignore = "0.4.18"
thiserror = "1.0.30"
similar = "2.1.0"
vfs = { path = "../vfs" }
lib = { path = "../lib" }

[dependencies.serde_json]
version = "1.0.68"
optional = true

[dependencies.serde]
version = "1.0.68"
features = [ "derive" ]
optional = true

[features]
json = [ "lib/json-out", "serde_json", "serde" ]
